language: php
matrix:
  include:
  - os: linux
    compiler: gcc
    sudo: required
    dist: xenial
install:
- export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- travis_retry sudo apt-get install software-properties-common
- travis_retry sudo add-apt-repository -y ppa:ondrej/php
- travis_retry sudo apt-get update
- travis_retry sudo apt install -y php7.2 php7.2-dev php7.2-cli
  php7.2-mbstring php7.2-curl php7.2-xml php7.2-intl
- curl -sS https://getcomposer.org/installer -o composer-setup.php
- sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
before_script:
- composer install
- sh $TRAVIS_BUILD_DIR/vendor/virgil/crypto-wrapper/_extensions/setup.sh -all -vendor
script: vendor/bin/phpunit --configuration phpunit.xml